In [ ]:
import numpy as np

In [ ]:
a = [1, 5]
b = [2, 6]
c = a + b
print(c)

In [ ]:
print(c)

In [ ]:
print (c)

In [ ]:
c = np.add(a, b)
print (c)

In [ ]:
c = np.add(a, b)
print (c)

In [ ]:
!dir

In [ ]:
!dir

In [ ]:
%lsmagic


In [2]:
import  numpy as np


In [ ]:
x = np.arrange(-10, 11, 2)
x

In [3]:
import  numpy as np


a =[i for i in range (10)]


In [4]:
a = [i for i in range(10)]

In [5]:
a


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
arr2 = np.array([[1, 6],
                [2, 7],
                [3, 8],
                [4, 9],
                [5,10]])
print(arr2)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [7]:
a = np.arange(10).reshape(5,2)
a


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
 np.mean(a, axis = 0)


array([4., 5.])

In [5]:
import  numpy as np


In [6]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10],[1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [7]:
 np.mean(a, axis = 0)

array([2. , 8.4])

In [8]:
import pickle
import pandas as pd

In [10]:
mean_a =np.mean(a, axis = 0)

In [12]:
mean_a =np.mean(a, axis = 0)
mean_a 

array([2. , 8.4])

In [14]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10],[1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
mean_a =np.mean(a, axis = 0)
mean_a 

array([2. , 8.4])

In [17]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [18]:
a_centered[0]

array([-1. , -2.4])

In [19]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [20]:
a_centered_sp = a_centered_sp / (len(a_centered) -1)
a_centered_sp

2.0

In [21]:
np_cov = np.cov(m=a.T)[0, 1]
np_cov == a_centered_sp

True

In [22]:
authors = pd.DataFrame({'authors_id': [1, 2, 3], "authors_name":['Turgenev', 'Chehov', 'Ostrovcki']})
authors

authors_id authors_name
0           1     Turgenev
1           2       Chehov
2           3    Ostrovcki

In [2]:
import numpy as np
import pickle
import pandas as pd

In [3]:
authors = pd.DataFrame({'authors_id': [1, 2, 3], "authors_name":['Turgenev', 'Chehov', 'Ostrovcki']})
authors

authors_id authors_name
0           1     Turgenev
1           2       Chehov
2           3    Ostrovcki

In [4]:
book = pd.DataFrame({'authors_id': [1, 1, 1, 2, 2, 3, 3], 
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                    'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price': [450, 300, 350, 500, 450, 370, 290]})
book

authors_id            book_title  price
0           1           Отцы и дети    450
1           1                 Рудин    300
2           1     Дворянское гнездо    350
3           2      Толстый и тонкий    500
4           2       Дама с собачкой    450
5           3                 Гроза    370
6           3  Таланты и поклонники    290

In [5]:
import numpy as np
import pickle
import pandas as pd

In [7]:
book = pd.DataFrame({'authors_id': [1, 1, 1, 2, 2, 3, 3], 
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                    'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price': [450, 300, 350, 500, 450, 370, 290]})
book

authors_id            book_title  price
0           1           Отцы и дети    450
1           1                 Рудин    300
2           1     Дворянское гнездо    350
3           2      Толстый и тонкий    500
4           2       Дама с собачкой    450
5           3                 Гроза    370
6           3  Таланты и поклонники    290

In [8]:
autors_price = pd.merge(authors, book, on='authors_id', how='outer')
autors_price

authors_id authors_name            book_title  price
0           1     Turgenev           Отцы и дети    450
1           1     Turgenev                 Рудин    300
2           1     Turgenev     Дворянское гнездо    350
3           2       Chehov      Толстый и тонкий    500
4           2       Chehov       Дама с собачкой    450
5           3    Ostrovcki                 Гроза    370
6           3    Ostrovcki  Таланты и поклонники    290

In [9]:
top5 = autors_price.sort_values(by='price', inplace=False)[::-1][:5]
top5.reset_index(drop=True, inplace=True)
top5

authors_id authors_name         book_title  price
0           2       Chehov   Толстый и тонкий    500
1           2       Chehov    Дама с собачкой    450
2           1     Turgenev        Отцы и дети    450
3           3    Ostrovcki              Гроза    370
4           1     Turgenev  Дворянское гнездо    350

In [11]:
gb = autors_price.groupby('authors_name')
authors_stat = pd.DataFrame({'min_price': gb['price'].min(),
                            'max_price': gb['price'].max(),
                            'mean_price': gb['price'].mean()})
authors_stat

min_price  max_price  mean_price
authors_name                                  
Chehov              450        500  475.000000
Ostrovcki           290        370  330.000000
Turgenev            300        450  366.666667